all: build

rebuild: clean build
	gcc lab2.c -o lab2

build: max string sum
	gcc lab2.c -o lab2

max:
	gcc max.c -o max

string:
	gcc string.c -o string

sum:
	gcc sum_args.c -o sum

clean:
	rm -rf max string sum lab2